### ISSUE TITLE
what 's the version of python used in this project?

### ISSUE THREAD

**Issue by whucsu** [david-stojanovski/E-Pix2Vox-reconstruction#1]
Dear Sir, thanks for the sharing, and what 's the version of python used in this project? 
thanks..

**Comment by david-stojanovski** [comment]
The reconstruction network was verified as working using python 3.10 at time of publication.

**Comment by whucsu** [comment]
After using python=3.10 in conda enviroment, the installation occured some problems:

ERROR: Ignored the following versions that require a different python version: 2.82.1 Requires-Python >=3.7, <3.8
ERROR: Could not find a version that satisfies the requirement bpy==2.82.1 (from versions: 3.4.0, 3.5.0)
ERROR: No matching distribution found for bpy==2.82.1
