### ISSUE TITLE
can you check the requirement file ?

### ISSUE THREAD

**Issue by whucsu** [david-stojanovski/E-Pix2Vox-reconstruction#2]
After using python=3.10 in conda enviroment, the installation occured some problems:

ERROR: Ignored the following versions that require a different python version: 2.82.1 Requires-Python >=3.7, <3.8
ERROR: Could not find a version that satisfies the requirement bpy==2.82.1 (from versions: 3.4.0, 3.5.0)
ERROR: No matching distribution found for bpy==2.82.1

thanks.
best wishes.

**Comment by david-stojanovski** [comment]
Hi,

I have updated the requiremets.txt and some of the files, which contained some deprecated data types with the newer versions of numpy. I did some quick runs on the different parts of the code and things seem to be running as expected. Let me know if there are still any issues with the updates

**Comment by whucsu** [comment]
> 

thanks, I will try.

**Comment by EITANSS** [comment]
Hey, whucsu, if you were able to run the net I would love it if you'll mail me- eitan.stern@weizmann.ac.il I've been trying to run the net for my research and had some problems.

Thanks in advance,

Eitan
